name: Release Workflow
permissions: {}

on:
  push:
    tags:
      - "*"

jobs:
  lint:
    name: Linters
    runs-on: ubuntu-latest
    permissions:
      contents: read # Fetch repository
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: zizmor
        uses: zizmorcore/zizmor-action@e639db99335bc9038abc0e066dfcd72e23d26fb4 # v0.3.0

      - name: typos
        uses: crate-ci/typos@2d0ce569feab1f8752f1dde43cc2f2aa53236e06 # v1.40.0

      - name: Ruff
        uses: astral-sh/ruff-action@57714a7c8a2e59f32539362ba31877a1957dded1 # v3.5.1

  wheel:
    name: Build wheel
    strategy:
      fail-fast: false
      matrix:
        os: ["macos-14", "ubuntu-22.04", "windows-latest"]
    runs-on: ${{ matrix.os }}
    needs: lint
    permissions:
      contents: read # Fetch repository
      actions: write # Upload artifact
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install CUDA 12.9 on Linux
        if: runner.os == 'Linux'
        run: |
          wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-keyring_1.1-1_all.deb
          sudo dpkg -i cuda-keyring_1.1-1_all.deb
          sudo apt-get update
          sudo apt-get -y install cuda-nvcc-12-9
          echo "CUDA_HOME=/usr/local/cuda-12.9" >> $GITHUB_ENV
          echo "/usr/local/cuda-12.9/bin" >> $GITHUB_PATH

      - name: Install CUDA 12.9 on Windows
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          $downloadUrl = "https://developer.download.nvidia.com/compute/cuda/12.9.1/local_installers/cuda_12.9.1_576.57_windows.exe"
          $dst = "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.9"
          New-Item -Path $dst -ItemType Directory -Force
          & "C:\msys64\usr\bin\wget" $downloadUrl -O "cuda.exe" -q
          & 'C:\Program Files\7-Zip\7z' x "cuda.exe" -o"cuda" -y cuda_nvcc/ cuda_cudart/ cuda_cccl/ visual_studio_integration/ libnvjitlink/
          Copy-Item -Path "cuda\cuda_nvcc\nvcc\*" -Destination $dst -Recurse -Force
          Copy-Item -Path "cuda\cuda_cudart\cudart\*" -Destination $dst -Recurse -Force
          Copy-Item -Path "cuda\cuda_cccl\thrust\*" -Destination $dst -Recurse -Force
          Write-Output "CUDA_HOME=$dst" >> $env:GITHUB_ENV
          Write-Output "$dst\bin" >> $env:GITHUB_PATH

      - name: Check CUDA installation
        if: runner.os != 'macOS'
        shell: bash
        run: |
          nvcc -V
          echo CUDA_HOME=$CUDA_HOME

      - name: Install uv
        uses: astral-sh/setup-uv@1e862dfacbd1d6d858c55d9b792c756523627244 # v7.1.4
        with:
          version: "latest"
          enable-cache: false

      - name: Install dependencies on Linux and Windows
        if: runner.os != 'macOS'
        run: |
          uv venv
          uv pip install setuptools numpy ninja
          uv pip install torch --index-url https://download.pytorch.org/whl/nightly/cu128

      - name: Install dependencies on macOS
        if: runner.os == 'macOS'
        run: |
          uv venv
          uv pip install setuptools numpy ninja
          uv pip install torch --index-url https://download.pytorch.org/whl/nightly/cpu

      - name: Build wheel
        run: uv build --wheel --no-build-isolation

      - name: Relabel the Linux wheel
        if: runner.os == 'Linux'
        run: |
          uvx --with patchelf auditwheel repair ./dist/*abi3-linux*.whl -w ./dist --plat manylinux_2_34_x86_64 --exclude "libtorch*" --exclude "libc10*" --exclude "libcu*"
          rm ./dist/*abi3-linux*.whl

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-wheel-${{ matrix.os }}
          path: ./dist/*

  sdist:
    name: Build sdist
    runs-on: ubuntu-latest
    permissions:
      contents: read # Fetch repository
      actions: write # Upload artifact
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@1e862dfacbd1d6d858c55d9b792c756523627244 # v7.1.4
        with:
          version: "latest"
          enable-cache: false

      - name: Build sdist
        run: uv build --sdist

      - name: Upload sdist
        uses: actions/upload-artifact@v5
        with:
          name: dist-sdist
          path: ./dist/*


  publish-to-pypi:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    needs: [wheel, sdist]
    environment:
      name: publish-to-pypi
    permissions:
      actions: read # Download artifact
      id-token: write # Needed for trusted publishing
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v6
        with:
          path: artifacts

      - name: Move the artifacts
        run: |
          mkdir ./dist
          mv ./artifacts/**/* ./dist

      - name: Install uv
        uses: astral-sh/setup-uv@1e862dfacbd1d6d858c55d9b792c756523627244 # v7.1.4
        with:
          version: "latest"
          enable-cache: false

      - name: Upload to PyPI
        run: uv publish --trusted-publishing always


  github-release:
    name: GitHub release
    runs-on: ubuntu-latest
    needs: [wheel, sdist]
    permissions:
      actions: read # Download artifact
      contents: write # Create GitHub release
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Download all artifacts
        uses: actions/download-artifact@v6
        with:
          path: artifacts

      - name: Move the artifacts
        run: |
          mkdir ./dist
          mv ./artifacts/**/* ./dist

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: gh release create "${GITHUB_REF#refs/tags/}" ./dist/*
